---
title: "Clean and Explore VZinfo BMI Data"
author: "Laurens Bogaardt"
date: "2023-09-21"
output:
  html_document:
    df_print: paged
    fig_width: 10
    fig.align: center
    toc: true
    toc_depth: 4
    toc_float: true
    theme: united
    code_folding: show
bibliography: ../A-Model-of-Individual-BMI-Trajectories.bib
link-citations: yes
---

# Introduction

Before we begin, we will need to load some packages.
[@tidyverse2019].

```{r results = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
```

# Load Input

[Placeholder for Text]

```{r}
trend.volwassenen.met.obesitas <- read_delim(
  file = "../Input-Data/VZinfo/trend-volwassenen-met-ob.csv",
  delim = ";",
  col_types = cols_only(
    "Category" = col_integer(),
    "mannen gestand.*" = col_double(),
    "vrouwen gestand.*" = col_double(),
    "mannen ongestand." = col_double(),
    "vrouwen ongestand." = col_double()
  )
)
trend.volwassenen.met.obesitas
```

[Placeholder for Text]

## Geslacht Trend Volwassenen met Overgewicht

[Placeholder for Text]

```{r}
trend.volwassenen.met.overgewicht <- read_delim(
  file = "../Input-Data/VZinfo/trend-volwassenen-met-ov.csv",
  delim = ";",
  col_types = cols_only(
    "Category" = col_integer(),
    "mannen gestand.*" = col_double(),
    "vrouwen gestand.*" = col_double(),
    "mannen ongestand." = col_double(),
    "vrouwen ongestand." = col_double()
  )
)
trend.volwassenen.met.overgewicht
```

[Placeholder for Text]

# Clean Data

[Placeholder for Text]

```{r}
bmi.by.year.and.sex <- trend.volwassenen.met.overgewicht %>%
  pivot_longer(
    cols = !Category,
    names_pattern = "(.*) (.*)",
    names_to = c("sex", "standardised"),
    values_to = "prevalence_[25,Inf)"
  ) %>%
  full_join(
    trend.volwassenen.met.obesitas %>%
      pivot_longer(
        cols = !Category,
        names_pattern = "(.*) (.*)",
        names_to = c("sex", "standardised"),
        values_to = "prevalence_[30,Inf)"
      ),
    by = c("Category", "sex", "standardised")
  ) %>%
  mutate(
    sex = recode_factor(
      sex,
      "mannen" = 0,
      "vrouwen" = 1
    ),
    year = Category,
    standardised = recode_factor(
      standardised,
      "ongestand." = 0,
      "gestand.*" = 1
    ),
    `prevalence_[25,30)` = round((`prevalence_[25,Inf)` - `prevalence_[30,Inf)`) / 100, 3),
    `prevalence_[30,Inf)` = round(`prevalence_[30,Inf)` / 100, 3)
  ) %>%
  pivot_longer(
    cols = c("prevalence_[25,30)", "prevalence_[30,Inf)"),
    names_pattern = "prevalence_(.*)",
    names_to = "bmi",
    values_to = "prevalence"
  ) %>%
  select(year, sex, bmi, standardised, prevalence) %>%
  arrange(year, sex, bmi, standardised, prevalence)
bmi.by.year.and.sex
```

[Placeholder for Text]

# Write Output

[Placeholder for Text]

```{r}
write_csv(
  x = bmi.by.year.and.sex,
  file = "../Output-Data/VZinfo.csv"
)
```

[Placeholder for Text]
